# Exercise | Make messy data tidy
## Clean up `relig_income.csv` file using `pandas.melt()`

In [2]:
# Load libraries
import pandas as pd

# Load data
df = pd.read_csv('data/tidy_messy_data/relig_income.csv')
df

,religion,<$10k,$10-20k,$20-30k,$30-40k,$40-50k,$50-75k,$75-100k,$100-150k,>150k,Don't know/refused
0,Agnostic,27,34,60,81,76,137,122,109,84,96
1,Atheist,12,27,37,52,35,70,73,59,74,76
2,Buddhist,27,21,30,34,33,58,62,39,53,54
3,Catholic,418,617,732,670,638,1116,949,792,633,1489
4,Don’t know/refused,15,14,15,11,10,35,21,17,18,116
5,Evangelical Prot,575,869,1064,982,881,1486,949,723,414,1529
6,Hindu,1,9,7,9,11,34,47,48,54,37
7,Historically Black Prot,228,244,236,238,197,223,131,81,78,339
8,Jehovah's Witness,20,27,24,24,21,30,15,11,6,37
9,Jewish,19,19,25,25,30,95,69,87,151,162
10,Mainline Prot,289,495,619,655,651,1107,939,753,634,1328
11,Mormon,29,40,48,51,56,112,85,49,42,69
12,Muslim,6,7,9,10,9,23,16,8,6,22
13,Orthodox,13,17,23,32,32,47,38,42,46,73
14,Other Christian,9,7,11,13,13,14,18,14,12,18
15,Other Faiths,20,33,40,46,49,63,46,40,41,71
16,Other World Religions,5,2,3,4,2,7,3,4,4,8
17,Unaffiliated,217,299,374,365,341,528,407,321,258,597

In [3]:
# Reshape the data using the melt function
tidy_df = pd.melt(df, id_vars='religion', var_name='income_range', value_name='count')
tidy_df

                  religion        income_range  count
0                 Agnostic               <$10k     27
1                  Atheist               <$10k     12
2                 Buddhist               <$10k     27
3                 Catholic               <$10k    418
4       Don’t know/refused               <$10k     15
..                     ...                 ...    ...
175               Orthodox  Don't know/refused     73
176        Other Christian  Don't know/refused     18
177           Other Faiths  Don't know/refused     71
178  Other World Religions  Don't know/refused      8
179           Unaffiliated  Don't know/refused    597

[180 rows x 3 columns]

## `weather.csv` data using `pandas.melt()`

In [4]:
# Load data
df2 = pd.read_csv('data/tidy_messy_data/weather.csv')
df2

,id,year,month,element,d1,d2,d3,d4,d5,d6,...,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31
0,MX17004,2010,1,TMAX,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,278.0,NaN
1,MX17004,2010,1,TMIN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,145.0,NaN
2,MX17004,2010,2,TMAX,NaN,273.0,241.0,NaN,NaN,NaN,...,NaN,299.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MX17004,2010,2,TMIN,NaN,144.0,144.0,NaN,NaN,NaN,...,NaN,107.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MX17004,2010,3,TMAX,NaN,NaN,NaN,NaN,321.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,MX17004,2010,3,TMIN,NaN,NaN,NaN,NaN,142.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MX17004,2010,4,TMAX,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,363.0,NaN,NaN,NaN,NaN
7,MX17004,2010,4,TMIN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,167.0,NaN,NaN,NaN,NaN
8,MX17004,2010,5,TMAX,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,332.0,NaN,NaN,NaN,NaN
9,MX17004,2010,5,TMIN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,182.0,NaN,NaN,NaN,NaN
10,MX17004,2010,6,TMAX,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,301.0,NaN,NaN
11,MX17004,2010,6,TMIN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.0,NaN,NaN
12,MX17004,2010,7,TMAX,NaN,NaN,286.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,MX17004,2010,7,TMIN,NaN,NaN,175.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,MX17004,2010,8,TMAX,NaN,NaN,NaN,NaN,296.0,NaN,...,NaN,264.0,NaN,297.0,NaN,NaN,NaN,280.0,NaN,254.0
15,MX17004,2010,8,TMIN,NaN,NaN,NaN,NaN,158.0,NaN,...,NaN,150.0,NaN,156.0,NaN,NaN,NaN,153.0,NaN,154.0
16,MX17004,2010,10,TMAX,NaN,NaN,NaN,NaN,270.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,312.0,NaN,NaN,NaN
17,MX17004,2010,10,TMIN,NaN,NaN,NaN,NaN,140.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,150.0,NaN,NaN,NaN
18,MX17004,2010,11,TMAX,NaN,313.0,NaN,272.0,263.0,NaN,...,NaN,NaN,NaN,NaN,281.0,277.0,NaN,NaN,NaN,NaN
19,MX17004,2010,11,TMIN,NaN,163.0,NaN,120.0,79.0,NaN,...,NaN,NaN,NaN,NaN,121.0,142.0,NaN,NaN,NaN,NaN
20,MX17004,2010,12,TMAX,299.0,NaN,NaN,NaN,NaN,278.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MX17004,2010,12,TMIN,138.0,NaN,NaN,NaN,NaN,105.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Mostly tidy data

In [12]:
tidy_df2 = pd.melt(
    df2,
    id_vars=['id', 'year', 'month', 'element'],
    var_name='day',
    value_name='temperature'
)

# drop rows with missing temperature values
tidy_df2 = tidy_df2.dropna(subset=['temperature'])
tidy_df2.reset_index()

    index       id  year  month element  day  temperature
0      20  MX17004  2010     12    TMAX   d1        299.0
1      21  MX17004  2010     12    TMIN   d1        138.0
2      24  MX17004  2010      2    TMAX   d2        273.0
3      25  MX17004  2010      2    TMIN   d2        144.0
4      40  MX17004  2010     11    TMAX   d2        313.0
..    ...      ...   ...    ...     ...  ...          ...
61    631  MX17004  2010      8    TMIN  d29        153.0
62    638  MX17004  2010      1    TMAX  d30        278.0
63    639  MX17004  2010      1    TMIN  d30        145.0
64    674  MX17004  2010      8    TMAX  d31        254.0
65    675  MX17004  2010      8    TMIN  d31        154.0

[66 rows x 7 columns]

### Tidy data

In [13]:
# Pivot the data to create separate columns for TMAX and TMIN
pivot_df = tidy_df2.pivot(
    index=['id', 'year', 'month', 'day'],
    columns='element',
    values='temperature'
).reset_index()

pivot_df

element       id  year  month  day   TMAX   TMIN
0        MX17004  2010      1  d30  278.0  145.0
1        MX17004  2010      2  d11  297.0  134.0
2        MX17004  2010      2   d2  273.0  144.0
3        MX17004  2010      2  d23  299.0  107.0
4        MX17004  2010      2   d3  241.0  144.0
5        MX17004  2010      3  d10  345.0  168.0
6        MX17004  2010      3  d16  311.0  176.0
7        MX17004  2010      3   d5  321.0  142.0
8        MX17004  2010      4  d27  363.0  167.0
9        MX17004  2010      5  d27  332.0  182.0
10       MX17004  2010      6  d17  280.0  175.0
11       MX17004  2010      6  d29  301.0  180.0
12       MX17004  2010      7  d14  299.0  165.0
13       MX17004  2010      7   d3  286.0  175.0
14       MX17004  2010      8  d13  298.0  165.0
15       MX17004  2010      8  d23  264.0  150.0
16       MX17004  2010      8  d25  297.0  156.0
17       MX17004  2010      8  d29  280.0  153.0
18       MX17004  2010      8  d31  254.0  154.0
19       MX17004  2010      8   d5  296.0  158.0
20       MX17004  2010      8   d8  290.0  173.0
21       MX17004  2010     10  d14  295.0  130.0
22       MX17004  2010     10  d15  287.0  105.0
23       MX17004  2010     10  d28  312.0  150.0
24       MX17004  2010     10   d5  270.0  140.0
25       MX17004  2010     10   d7  281.0  129.0
26       MX17004  2010     11   d2  313.0  163.0
27       MX17004  2010     11  d26  281.0  121.0
28       MX17004  2010     11  d27  277.0  142.0
29       MX17004  2010     11   d4  272.0  120.0
30       MX17004  2010     11   d5  263.0   79.0
31       MX17004  2010     12   d1  299.0  138.0
32       MX17004  2010     12   d6  278.0  105.0